### ISSUE TITLE
GUI error

### ISSUE THREAD

**Issue by rauljim** [rauljim/pymdht#15]
GUI crashes when I select a capture file and then click on 'load' before selecting any info_hash.

Retrieving all to ui/torrent_pages/all.html ... DONE
Traceback (most recent call last):
  File "/home/raul/git/pymdht/ui/graphical_display.py", line 342, in start_processing
    self.precalculation_nextstep()
  File "/home/raul/git/pymdht/ui/graphical_display.py", line 580, in precalculation_nextstep
    self.nextstepprocessing(self.ptr)
  File "/home/raul/git/pymdht/ui/graphical_display.py", line 639, in nextstepprocessing
    if(self.main_list[i][1]=='bogus'):
IndexError: list index out of range

**Comment by rauljim** [comment]
I think the problem comes from the fact that your were using a (very) old version of core/message.py

**Comment by rauljim** [comment]
I added core/old_message.py as a temporary solution. Now, GUI works fine on Linux.

Got a new GUI error on Windows:

Retrieving all to ui/torrent_pages\all.html ... DONE
Traceback (most recent call last):
  File "C:\Users\raul\Desktop\pymdht\ui\graphical_display.py", line 392, in on_b
rowse
    self.reinitialize_param()
  File "C:\Users\raul\Desktop\pymdht\ui\graphical_display.py", line 347, in rein
itialize_param
    self.printing()
  File "C:\Users\raul\Desktop\pymdht\ui\graphical_display.py", line 500, in prin
ting
    dc = wx.PaintDC(self.panel1)
  File "c:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx_gdi.py", line 4823,
 in **init**
    _gdi_.PaintDC_swiginit(self,_gdi_.new_PaintDC(_args, *_kwargs))
wx._core.PyAssertionError: C++ assertion "wxAssertFailure" failed at ....\src\m
sw\dcclient.cpp(219) in wxPaintDC::wxPaintDC(): wxPaintDC may be created only in
 EVT_PAINT handler!

**Comment by csasm** [comment]
Hi!

I have removed the load button, i hope that this issue has been resolved

**Comment by rauljim** [comment]
Good!

When you commit the changes you can write a message like "bla bla bla (issue #15 closed)". Github will link #15 with issue 15, which is quite cool. Example:
https://github.com/ytakano/libcage/commit/90d4d63caf9a05b711d99d6c32719f0f69d7d22b

Don't forget to close the issue after you push the commit to github.
