### ISSUE TITLE
Minitwisted crashed (Windows 7)

### ISSUE THREAD

**Issue by rauljim** [rauljim/pymdht#19]
Need to check that plugins implement ALL handlers.

2011-08-24 15:17:36,796 WARNING querier.py:95 - get_related_query()
No query for this response
{'y': 'r', 'r': {'nodes': 'gLB!1&I\x88\xc5PZ\xe65\xa3\xba\xfe\x88\x18L\xb5b\xb1\
xfcO"KgJ\xefl8\x1a\xd9\x9bs\x84\xac\xa6\x0eq\xf6H\xa0J&\x19\xd4t|\x84\xc8\xd5gJ\
xa7\xe373\xbf\xfa\x99x03km2\x9e~Ja\xfbY\xa3R\x8c6fgJF:\xa8\xd3\xff\xa5\x9a\x15\x
cc\xc39B\x01Jt\x90\xdc<M\x7f\xb9\x90*\xdbgJ\xecY\x86N\xfc\x10\xe4\xeaE\x1fF_U\xe
2a\x1f&~\xdbI_O \x01gN\xbd?\xa1\xa8\xd5%\xb7\xfc\xe7\x8e\xe7)\x8f\x17\xe5@\xbfd\
xd5\x9b\xcd\x1b\'\x10gJ\xce\xccX|\xf8\x1c\xaa\x8b\x13q\xdd\xaa\x15&\x14\xd4w\xeb
p\x9e\xcdV<\xe1g@\xab#\x03\x83\x9c\x84\\x91\x92\xc9\xfa\xd02a\x13\xb9g\x82S\xa7
m[\xf6I', 'id': 'gSS\xba?\xb0\xcb\xe5H:\x85\xee\xc7+\xa5\xfa\x9f\xef\xb2\x04'},
't': 'S\x00'}
source: ('114.40.179.231', 16447)

2011-08-24 15:17:44,446 WARNING querier.py:89 - get_related_query()
Error message received:
{'y': 'e', 'e': [203, 'Incorrect token in announce_peer'], 't': '\xcd\x00', 'v':
 'LT\x00\x0e'}
Source: ('82.242.253.113', 6882)

2011-08-24 15:17:44,446 CRITICAL minitwisted.py:89 - run()
MINITWISTED CRASHED

2011-08-24 15:17:44,446 ERROR minitwisted.py:90 - run()
MINITWISTED CRASHED
Traceback (most recent call last):
  File "C:\Users\raul\Desktop\pymdht\core\minitwisted.py", line 87, in run
    self._protected_run()
  File "C:\Users\raul\Desktop\pymdht\core\minitwisted.py", line 160, in _protect
ed_run
    datagram_received)
  File "C:\Users\raul\Desktop\pymdht\core\controller.py", line 288, in on_datagr
am_received
    exp_queries_to_send = self._experimental_m.on_error_received(msg, related_qu
ery)
AttributeError: ExperimentalManager instance has no attribute 'on_error_received
'

**Comment by rauljim** [comment]
11.8.2 solves this problem but it would be good to have automatic checks, so this doesn't happen again.
