### ISSUE TITLE
Got error in graphical display

### ISSUE THREAD

**Issue by rauljim** [rauljim/pymdht#27]
This is code on my develop branch (https://github.com/rauljim/pymdht/tree/224fb902e7050bb7e6f667d4c37ffb11b4834997) , which is not completely up-to-date with your branch. This bug might be solved in your branch.

The second exception seems to be that you don't call pymdht.stop() when the user click 'exit', so the minitwisted thread dies without notice.

$ ./interactive_dht.py --gui
Using the following plug-ins:
- plugins/routing_nice_rtt.py
- plugins/lookup_a4.py
- core/exp_plugin_template.py
  Path: /home/raul/.pymdht
  Private DHT name: None
  debug mode: False
  Slow Motion
  0.01354
  0.03718
  0.03415
  0.02917
  0.01354
  0.1356
  0.02917
  0.03102
  0.03415
  0.2445
  0.03718
  0.1962
  0.03102
  0.2583
  0.1356
  0.3648
  Traceback (most recent call last):
  File "/home/raul/git/pymdht/ui/graphical_display.py", line 501, in on_left_click
    self.left_click_processing(dc)
  File "/home/raul/git/pymdht/ui/graphical_display.py", line 484, in left_click_processing
    if not(ninfo2==False):
  UnboundLocalError: local variable 'ninfo2' referenced before assignment
  0.1962
  0.15
  0.2445
  0.2486
  0.2583
  0.05214
  0.05214
  0.08821
  0.15
  0.3491
  0.08821
  0.0
  0.3648
  0.3263
  0.2486
  0.0
  0.3491
  0.0
  0.3263
  0.0
  0.0
  0.0
  0.0
  0.3093
  0.3093
  0.0
  Exception in thread Thread-1 (most likely raised during interpreter shutdown):
  Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/home/raul/git/pymdht/core/minitwisted.py", line 91, in run
  File "/home/raul/git/pymdht/core/minitwisted.py", line 105, in run2
  <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'critical'

**Comment by csasm** [comment]
This issue has been solved with suggested dht.stop() method
